
from difflib import SequenceMatcher
import numpy as np
import pandas as pd


FEATURE_CATALOG = {

    # =========================================================
    # 1. INCOME STATEMENT
    # =========================================================

    "revenue": {
        "name": "Revenue",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Total revenue generated by the company."
    },
    "cost_of_revenue": {
        "name": "Cost of Revenue",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Direct costs associated with generating revenue."
    },
    "gross_profit": {
        "name": "Gross Profit",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Revenue remaining after cost of revenue."
    },
    "operating_expenses": {
        "name": "Operating Expenses",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Expenses incurred in operating the business."
    },
    "operating_income": {
        "name": "Operating Income",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Profit generated from core operations."
    },
    "ebit": {
        "name": "EBIT",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Earnings before interest and taxes."
    },
    "ebitda": {
        "name": "EBITDA",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Earnings before interest, taxes, depreciation and amortization."
    },
    "depreciation": {
        "name": "Depreciation",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Depreciation expense."
    },
    "amortization": {
        "name": "Amortization",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Amortization expense."
    },
    "depreciation_amortization": {
        "name": "Depreciation & Amortization",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Combined depreciation and amortization."
    },
    "interest_expense": {
        "name": "Interest Expense",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Interest cost on borrowings."
    },
    "interest_income": {
        "name": "Interest Income",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Income earned from interest-bearing assets."
    },
    "income_before_tax": {
        "name": "Income Before Tax",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Profit before income tax."
    },
    "income_tax": {
        "name": "Income Tax",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Income tax expense."
    },
    "net_income": {
        "name": "Net Income",
        "category": "Income Statement",
        "unit": "currency",
        "description": "Profit after all expenses and taxes."
    },

    # =========================================================
    # 2. PROFITABILITY & MARGINS
    # =========================================================

    "gross_margin": {
        "name": "Gross Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Gross profit as a percentage of revenue."
    },
    "operating_margin": {
        "name": "Operating Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Operating income as a percentage of revenue."
    },
    "ebit_margin": {
        "name": "EBIT Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "EBIT as a percentage of revenue."
    },
    "ebitda_margin": {
        "name": "EBITDA Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "EBITDA as a percentage of revenue."
    },
    "net_profit_margin": {
        "name": "Net Profit Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Net income as a percentage of revenue."
    },
    "pretax_margin": {
        "name": "Pre-Tax Margin",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Income before tax as a percentage of revenue."
    },
    "tax_rate": {
        "name": "Effective Tax Rate",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Income tax as a percentage of pre-tax income."
    },
    "roe": {
        "name": "Return on Equity",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Return generated on shareholder equity."
    },
    "roa": {
        "name": "Return on Assets",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Return generated from company assets."
    },
    "roi": {
        "name": "Return on Investment",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Return generated on investment."
    },
    "rote": {
        "name": "Return on Tangible Equity",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Return generated on tangible shareholder equity."
    },
    "return_on_capital": {
        "name": "Return on Capital",
        "category": "Profitability",
        "unit": "percentage",
        "description": "Return generated on invested capital."
    },
    "profit_per_employee": {
        "name": "Profit per Employee",
        "category": "Profitability",
        "unit": "currency",
        "description": "Net income generated per employee."
    },

    # =========================================================
    # 3. BALANCE SHEET
    # =========================================================

    "total_assets": {
        "name": "Total Assets",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Total assets owned by the company."
    },
    "current_assets": {
        "name": "Current Assets",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Assets expected to be converted to cash within the operating cycle."
    },
    "non_current_assets": {
        "name": "Non-Current Assets",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Long-term assets."
    },
    "cash": {
        "name": "Cash & Cash Equivalents",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Cash and highly liquid cash equivalents."
    },
    "inventory": {
        "name": "Inventory",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Inventory held by the company."
    },
    "accounts_receivable": {
        "name": "Accounts Receivable",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Amounts owed by customers."
    },
    "accounts_payable": {
        "name": "Accounts Payable",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Amounts owed to suppliers."
    },
    "total_liabilities": {
        "name": "Total Liabilities",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Total obligations of the company."
    },
    "current_liabilities": {
        "name": "Current Liabilities",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Short-term obligations."
    },
    "long_term_debt": {
        "name": "Long-Term Debt",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Debt due beyond the short-term period."
    },
    "short_term_debt": {
        "name": "Short-Term Debt",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Debt due in the short term."
    },
    "total_debt": {
        "name": "Total Debt",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Total interest-bearing debt."
    },
    "share_holder_equity": {
        "name": "Shareholder Equity",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Residual value attributable to shareholders."
    },
    "retained_earnings": {
        "name": "Retained Earnings",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Accumulated earnings retained in the business."
    },
    "working_capital": {
        "name": "Working Capital",
        "category": "Balance Sheet",
        "unit": "currency",
        "description": "Current assets minus current liabilities."
    },

    # =========================================================
    # 4. LIQUIDITY
    # =========================================================

    "current_ratio": {
        "name": "Current Ratio",
        "category": "Liquidity",
        "unit": "ratio",
        "description": "Current assets divided by current liabilities."
    },
    "quick_ratio": {
        "name": "Quick Ratio",
        "category": "Liquidity",
        "unit": "ratio",
        "description": "Liquid current assets divided by current liabilities."
    },
    "cash_ratio": {
        "name": "Cash Ratio",
        "category": "Liquidity",
        "unit": "ratio",
        "description": "Cash and equivalents divided by current liabilities."
    },
    "working_capital_ratio": {
        "name": "Working Capital Ratio",
        "category": "Liquidity",
        "unit": "ratio",
        "description": "Working capital relative to revenue."
    },
    "operating_cash_flow_ratio": {
        "name": "Operating Cash Flow Ratio",
        "category": "Liquidity",
        "unit": "ratio",
        "description": "Operating cash flow relative to current liabilities."
    },
    "cash_to_assets": {
        "name": "Cash to Assets",
        "category": "Liquidity",
        "unit": "percentage",
        "description": "Cash as a percentage of total assets."
    },

    # =========================================================
    # 5. LEVERAGE & SOLVENCY
    # =========================================================

    "debt_equity_ratio": {
        "name": "Debt to Equity Ratio",
        "category": "Leverage",
        "unit": "ratio",
        "description": "Debt relative to shareholder equity."
    },
    "debt_asset_ratio": {
        "name": "Debt to Asset Ratio",
        "category": "Leverage",
        "unit": "percentage",
        "description": "Debt relative to total assets."
    },
    "liabilities_asset_ratio": {
        "name": "Liabilities to Assets",
        "category": "Leverage",
        "unit": "percentage",
        "description": "Total liabilities relative to total assets."
    },
    "equity_asset_ratio": {
        "name": "Equity to Assets",
        "category": "Leverage",
        "unit": "percentage",
        "description": "Shareholder equity relative to total assets."
    },
    "interest_coverage": {
        "name": "Interest Coverage Ratio",
        "category": "Leverage",
        "unit": "ratio",
        "description": "Ability to cover interest expense from operating earnings."
    },
    "debt_service_coverage": {
        "name": "Debt Service Coverage Ratio",
        "category": "Leverage",
        "unit": "ratio",
        "description": "Ability to cover debt service obligations."
    },
    "net_debt": {
        "name": "Net Debt",
        "category": "Leverage",
        "unit": "currency",
        "description": "Total debt less cash and equivalents."
    },
    "net_debt_to_ebitda": {
        "name": "Net Debt to EBITDA",
        "category": "Leverage",
        "unit": "ratio",
        "description": "Net debt relative to EBITDA."
    },

    # =========================================================
    # 6. CASH FLOW
    # =========================================================

    "cash_flow_from_operating": {
        "name": "Operating Cash Flow",
        "category": "Cash Flow",
        "unit": "currency",
        "description": "Cash generated from operating activities."
    },
    "cash_flow_from_investing": {
        "name": "Investing Cash Flow",
        "category": "Cash Flow",
        "unit": "currency",
        "description": "Cash flow from investing activities."
    },
    "cash_flow_from_financial_activities": {
        "name": "Financing Cash Flow",
        "category": "Cash Flow",
        "unit": "currency",
        "description": "Cash flow from financing activities."
    },
    "free_cash_flow": {
        "name": "Free Cash Flow",
        "category": "Cash Flow",
        "unit": "currency",
        "description": "Cash remaining after required capital investment."
    },
    "free_cash_flow_per_share": {
        "name": "Free Cash Flow per Share",
        "category": "Cash Flow",
        "unit": "currency",
        "description": "Free cash flow generated per share."
    },
    "operating_cash_flow_margin": {
        "name": "Operating Cash Flow Margin",
        "category": "Cash Flow",
        "unit": "percentage",
        "description": "Operating cash flow as a percentage of revenue."
    },
    "free_cash_flow_margin": {
        "name": "Free Cash Flow Margin",
        "category": "Cash Flow",
        "unit": "percentage",
        "description": "Free cash flow as a percentage of revenue."
    },
    "cash_conversion_ratio": {
        "name": "Cash Conversion Ratio",
        "category": "Cash Flow",
        "unit": "ratio",
        "description": "Operating cash flow relative to net income."
    },
    "cash_flow_to_debt": {
        "name": "Cash Flow to Debt",
        "category": "Cash Flow",
        "unit": "percentage",
        "description": "Operating cash flow relative to total debt."
    },
    "investing_to_operating_cash": {
        "name": "Investing to Operating Cash Flow",
        "category": "Cash Flow",
        "unit": "ratio",
        "description": "Investing cash flow relative to operating cash flow."
    },

    # =========================================================
    # 7. EFFICIENCY
    # =========================================================

    "asset_turnover": {
        "name": "Asset Turnover",
        "category": "Efficiency",
        "unit": "ratio",
        "description": "Revenue generated per unit of assets."
    },
    "inventory_turnover": {
        "name": "Inventory Turnover",
        "category": "Efficiency",
        "unit": "ratio",
        "description": "Cost of revenue relative to inventory."
    },
    "receivable_turnover": {
        "name": "Receivable Turnover",
        "category": "Efficiency",
        "unit": "ratio",
        "description": "Revenue relative to accounts receivable."
    },
    "payable_turnover": {
        "name": "Payable Turnover",
        "category": "Efficiency",
        "unit": "ratio",
        "description": "Cost of revenue relative to accounts payable."
    },
    "days_inventory": {
        "name": "Days Inventory Outstanding",
        "category": "Efficiency",
        "unit": "days",
        "description": "Average number of days inventory remains outstanding."
    },
    "days_receivable": {
        "name": "Days Sales Outstanding",
        "category": "Efficiency",
        "unit": "days",
        "description": "Average number of days to collect receivables."
    },
    "days_payable": {
        "name": "Days Payable Outstanding",
        "category": "Efficiency",
        "unit": "days",
        "description": "Average number of days taken to pay suppliers."
    },
    "cash_conversion_cycle": {
        "name": "Cash Conversion Cycle",
        "category": "Efficiency",
        "unit": "days",
        "description": "Time required to convert operating investment into cash."
    },
    "revenue_per_employee": {
        "name": "Revenue per Employee",
        "category": "Efficiency",
        "unit": "currency",
        "description": "Revenue generated per employee."
    },
    "ebitda_per_employee": {
        "name": "EBITDA per Employee",
        "category": "Efficiency",
        "unit": "currency",
        "description": "EBITDA generated per employee."
    },

    # =========================================================
    # 8. MARKET & PER SHARE
    # =========================================================

    "earning_per_share": {
        "name": "Earnings per Share",
        "category": "Market & Per Share",
        "unit": "currency",
        "description": "Net income attributable to each share."
    },
    "market_capin_b_usd": {
        "name": "Market Capitalization",
        "category": "Market & Per Share",
        "unit": "currency",
        "description": "Total market value of equity."
    },
    "pe_ratio": {
        "name": "Price to Earnings Ratio",
        "category": "Market & Per Share",
        "unit": "ratio",
        "description": "Market price relative to earnings per share."
    },
    "pb_ratio": {
        "name": "Price to Book Ratio",
        "category": "Market & Per Share",
        "unit": "ratio",
        "description": "Market value relative to book value."
    },
    "dividend_yield": {
        "name": "Dividend Yield",
        "category": "Market & Per Share",
        "unit": "percentage",
        "description": "Dividend return relative to market value."
    },
    "earnings_yield": {
        "name": "Earnings Yield",
        "category": "Market & Per Share",
        "unit": "percentage",
        "description": "Earnings relative to market value."
    },
    "book_value_per_share": {
        "name": "Book Value per Share",
        "category": "Market & Per Share",
        "unit": "currency",
        "description": "Book equity attributable to each share."
    },
    "market_cap_to_revenue": {
        "name": "Market Cap to Revenue",
        "category": "Market & Per Share",
        "unit": "ratio",
        "description": "Market capitalization relative to revenue."
    },
    "market_cap_to_ebitda": {
        "name": "Market Cap to EBITDA",
        "category": "Market & Per Share",
        "unit": "ratio",
        "description": "Market capitalization relative to EBITDA."
    },
    "market_cap_to_net_income": {
        "name": "Market Cap to Net Income",
        "category": "Market & Per Share",
        "unit": "ratio",
        "description": "Market capitalization relative to net income."
    },

    # =========================================================
    # 9. GROWTH & TREND
    # =========================================================

    "revenue_yoy": {
        "name": "Revenue YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year revenue growth."
    },
    "gross_profit_yoy": {
        "name": "Gross Profit YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year gross profit growth."
    },
    "ebitda_yoy": {
        "name": "EBITDA YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year EBITDA growth."
    },
    "net_income_yoy": {
        "name": "Net Income YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year net income growth."
    },
    "equity_yoy": {
        "name": "Equity YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year shareholder equity growth."
    },
    "assets_yoy": {
        "name": "Assets YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year asset growth."
    },
    "debt_yoy": {
        "name": "Debt YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year debt growth."
    },
    "operating_cash_flow_yoy": {
        "name": "Operating Cash Flow YoY Growth",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Year-over-year operating cash flow growth."
    },
    "revenue_cagr": {
        "name": "Revenue CAGR",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Compound annual growth rate of revenue."
    },
    "net_income_cagr": {
        "name": "Net Income CAGR",
        "category": "Growth & Trend",
        "unit": "percentage",
        "description": "Compound annual growth rate of net income."
    },

    # =========================================================
    # 10. FINANCIAL QUALITY & RISK
    # =========================================================

    "earnings_quality": {
        "name": "Earnings Quality",
        "category": "Financial Quality & Risk",
        "unit": "ratio",
        "description": "Relationship between cash generation and reported earnings."
    },
    "profitability_trend": {
        "name": "Profitability Trend",
        "category": "Financial Quality & Risk",
        "unit": "percentage",
        "description": "Trend in profitability over time."
    },
    "margin_expansion": {
        "name": "Margin Expansion",
        "category": "Financial Quality & Risk",
        "unit": "percentage_points",
        "description": "Change in net profit margin."
    },
    "margin_compression": {
        "name": "Margin Compression",
        "category": "Financial Quality & Risk",
        "unit": "percentage_points",
        "description": "Decline in net profit margin."
    },
    "revenue_profit_divergence": {
        "name": "Revenue-Profit Divergence",
        "category": "Financial Quality & Risk",
        "unit": "percentage_points",
        "description": "Difference between revenue growth and net income growth."
    },
    "debt_growth_vs_revenue_growth": {
        "name": "Debt Growth vs Revenue Growth",
        "category": "Financial Quality & Risk",
        "unit": "percentage_points",
        "description": "Difference between debt growth and revenue growth."
    },
    "cash_flow_profit_gap": {
        "name": "Cash Flow-Profit Gap",
        "category": "Financial Quality & Risk",
        "unit": "percentage",
        "description": "Difference between operating cash flow and net income growth."
    },
    "financial_leverage": {
        "name": "Financial Leverage",
        "category": "Financial Quality & Risk",
        "unit": "ratio",
        "description": "Assets supported per unit of shareholder equity."
    },
    "risk_score": {
        "name": "Financial Risk Score",
        "category": "Financial Quality & Risk",
        "unit": "score",
        "description": "Composite financial risk indicator."
    },
    "financial_health_score": {
        "name": "Financial Health Score",
        "category": "Financial Quality & Risk",
        "unit": "score",
        "description": "Composite financial health indicator."
    },

    # =========================================================
    # 11. BUSINESS SCALE
    # =========================================================

    "number_of_employees": {
        "name": "Number of Employees",
        "category": "Business Scale",
        "unit": "count",
        "description": "Number of employees."
    },
    "revenue_growth_rate": {
        "name": "Revenue Growth Rate",
        "category": "Business Scale",
        "unit": "percentage",
        "description": "Rate of change in revenue."
    },
    "profit_growth_rate": {
        "name": "Profit Growth Rate",
        "category": "Business Scale",
        "unit": "percentage",
        "description": "Rate of change in net income."
    },
    "employee_growth_rate": {
        "name": "Employee Growth Rate",
        "category": "Business Scale",
        "unit": "percentage",
        "description": "Rate of change in employee count."
    },
    "revenue_per_employee_growth": {
        "name": "Revenue per Employee Growth",
        "category": "Business Scale",
        "unit": "percentage",
        "description": "Growth in revenue generated per employee."
    },

    # =========================================================
    # 12. MACROECONOMIC CONTEXT
    # =========================================================

    "inflation_ratein_us": {
        "name": "US Inflation Rate",
        "category": "Macroeconomic Context",
        "unit": "percentage",
        "description": "US inflation rate associated with the financial period."
    },
    "real_revenue_growth": {
        "name": "Real Revenue Growth",
        "category": "Macroeconomic Context",
        "unit": "percentage",
        "description": "Revenue growth adjusted for inflation."
    },
    "real_profit_growth": {
        "name": "Real Profit Growth",
        "category": "Macroeconomic Context",
        "unit": "percentage",
        "description": "Profit growth adjusted for inflation."
    }
}


def get_feature_count():
    return len(FEATURE_CATALOG)


def get_feature_catalog():
    return FEATURE_CATALOG


# ============================================================
# 115-FEATURE ANALYTICS ENGINE
# ============================================================

DERIVED_FEATURES = {

    "gross_margin": lambda d: d["gross_profit"] / d["revenue"] * 100,

    "operating_margin": lambda d: d["operating_income"] / d["revenue"] * 100,

    "ebit_margin": lambda d: d["ebit"] / d["revenue"] * 100,

    "ebitda_margin": lambda d: d["ebitda"] / d["revenue"] * 100,

    "net_profit_margin": lambda d: d["net_income"] / d["revenue"] * 100,

    "pretax_margin": lambda d: d["income_before_tax"] / d["revenue"] * 100,

    "tax_rate": lambda d: d["income_tax"] / d["income_before_tax"] * 100,

    "working_capital": lambda d: d["current_assets"] - d["current_liabilities"],

    "working_capital_ratio": lambda d: (
        d["working_capital"] / d["revenue"]
    ),

    "debt_asset_ratio": lambda d: (
        d["total_debt"] / d["total_assets"] * 100
    ),

    "liabilities_asset_ratio": lambda d: (
        d["total_liabilities"] / d["total_assets"] * 100
    ),

    "equity_asset_ratio": lambda d: (
        d["share_holder_equity"] / d["total_assets"] * 100
    ),

    "net_debt": lambda d: (
        d["total_debt"] - d["cash"]
    ),

    "net_debt_to_ebitda": lambda d: (
        d["net_debt"] / d["ebitda"]
    ),

    "operating_cash_flow_margin": lambda d: (
        d["cash_flow_from_operating"] / d["revenue"] * 100
    ),

    "free_cash_flow_margin": lambda d: (
        d["free_cash_flow"] / d["revenue"] * 100
    ),

    "cash_conversion_ratio": lambda d: (
        d["cash_flow_from_operating"] / d["net_income"]
    ),

    "cash_flow_to_debt": lambda d: (
        d["cash_flow_from_operating"] / d["total_debt"] * 100
    ),

    "asset_turnover": lambda d: (
        d["revenue"] / d["total_assets"]
    ),

    "inventory_turnover": lambda d: (
        d["cost_of_revenue"] / d["inventory"]
    ),

    "receivable_turnover": lambda d: (
        d["revenue"] / d["accounts_receivable"]
    ),

    "payable_turnover": lambda d: (
        d["cost_of_revenue"] / d["accounts_payable"]
    ),

    "days_inventory": lambda d: (
        365 / d["inventory_turnover"]
    ),

    "days_receivable": lambda d: (
        365 / d["receivable_turnover"]
    ),

    "days_payable": lambda d: (
        365 / d["payable_turnover"]
    ),

    "cash_conversion_cycle": lambda d: (
        d["days_inventory"]
        + d["days_receivable"]
        - d["days_payable"]
    ),

    "revenue_per_employee": lambda d: (
        d["revenue"] / d["number_of_employees"]
    ),

    "ebitda_per_employee": lambda d: (
        d["ebitda"] / d["number_of_employees"]
    ),

    "profit_per_employee": lambda d: (
        d["net_income"] / d["number_of_employees"]
    ),

    "earnings_yield": lambda d: (
        d["net_income"] / (d["market_capin_b_usd"] * 1000) * 100
    ),

    "market_cap_to_revenue": lambda d: (
        (d["market_capin_b_usd"] * 1000) / d["revenue"]
    ),

    "market_cap_to_ebitda": lambda d: (
        (d["market_capin_b_usd"] * 1000) / d["ebitda"]
    ),

    "market_cap_to_net_income": lambda d: (
        (d["market_capin_b_usd"] * 1000) / d["net_income"]
    ),

    "financial_leverage": lambda d: (
        d["total_assets"] / d["share_holder_equity"]
    ),

    "earnings_quality": lambda d: (
        d["cash_flow_from_operating"] / d["net_income"]
    ),

    "cash_to_assets": lambda d: (
        d["cash"] / d["total_assets"] * 100
    ),
}


YOY_BASE_FEATURES = {
    "revenue_yoy": "revenue",
    "gross_profit_yoy": "gross_profit",
    "ebitda_yoy": "ebitda",
    "net_income_yoy": "net_income",
    "equity_yoy": "share_holder_equity",
    "assets_yoy": "total_assets",
    "debt_yoy": "total_debt",
    "operating_cash_flow_yoy": "cash_flow_from_operating",
    "revenue_growth_rate": "revenue",
    "profit_growth_rate": "net_income",
    "employee_growth_rate": "number_of_employees",
}


def calculate_feature_values(df):
    """
    Calculate all features that can be directly obtained
    or mathematically derived from available financial data.
    """

    result = df.copy()

    for feature, formula in DERIVED_FEATURES.items():

        required = set()

        if feature == "gross_margin":
            required = {"gross_profit", "revenue"}

        elif feature == "operating_margin":
            required = {"operating_income", "revenue"}

        elif feature == "ebit_margin":
            required = {"ebit", "revenue"}

        elif feature == "ebitda_margin":
            required = {"ebitda", "revenue"}

        elif feature == "net_profit_margin":
            required = {"net_income", "revenue"}

        elif feature == "pretax_margin":
            required = {"income_before_tax", "revenue"}

        elif feature == "tax_rate":
            required = {"income_tax", "income_before_tax"}

        elif feature == "working_capital":
            required = {"current_assets", "current_liabilities"}

        elif feature == "working_capital_ratio":
            required = {"current_assets", "current_liabilities", "revenue"}

        elif feature == "debt_asset_ratio":
            required = {"total_debt", "total_assets"}

        elif feature == "liabilities_asset_ratio":
            required = {"total_liabilities", "total_assets"}

        elif feature == "equity_asset_ratio":
            required = {"share_holder_equity", "total_assets"}

        elif feature == "net_debt":
            required = {"total_debt", "cash"}

        elif feature == "net_debt_to_ebitda":
            required = {"total_debt", "cash", "ebitda"}

        elif feature == "operating_cash_flow_margin":
            required = {"cash_flow_from_operating", "revenue"}

        elif feature == "free_cash_flow_margin":
            required = {"free_cash_flow", "revenue"}

        elif feature == "cash_conversion_ratio":
            required = {"cash_flow_from_operating", "net_income"}

        elif feature == "cash_flow_to_debt":
            required = {"cash_flow_from_operating", "total_debt"}

        elif feature == "asset_turnover":
            required = {"revenue", "total_assets"}

        elif feature == "inventory_turnover":
            required = {"cost_of_revenue", "inventory"}

        elif feature == "receivable_turnover":
            required = {"revenue", "accounts_receivable"}

        elif feature == "payable_turnover":
            required = {"cost_of_revenue", "accounts_payable"}

        elif feature in {
            "days_inventory",
            "days_receivable",
            "days_payable"
        }:
            required = {
                "cost_of_revenue",
                "inventory",
                "revenue",
                "accounts_receivable",
                "accounts_payable"
            }

        elif feature == "cash_conversion_cycle":
            required = {
                "cost_of_revenue",
                "inventory",
                "revenue",
                "accounts_receivable",
                "accounts_payable"
            }

        elif feature in {
            "revenue_per_employee",
            "ebitda_per_employee",
            "profit_per_employee"
        }:
            required = {
                "number_of_employees"
            }

            if feature == "revenue_per_employee":
                required.add("revenue")

            elif feature == "ebitda_per_employee":
                required.add("ebitda")

            else:
                required.add("net_income")

        elif feature in {
            "earnings_yield",
            "market_cap_to_revenue",
            "market_cap_to_ebitda",
            "market_cap_to_net_income"
        }:
            required.add("market_capin_b_usd")

            if feature == "earnings_yield":
                required.add("net_income")

            elif feature == "market_cap_to_revenue":
                required.add("revenue")

            elif feature == "market_cap_to_ebitda":
                required.add("ebitda")

            else:
                required.add("net_income")

        elif feature == "financial_leverage":
            required = {
                "total_assets",
                "share_holder_equity"
            }

        elif feature == "earnings_quality":
            required = {
                "cash_flow_from_operating",
                "net_income"
            }

        elif feature == "cash_to_assets":
            required = {
                "cash",
                "total_assets"
            }

        if required and required.issubset(result.columns):

            try:
                result[feature] = formula(result)
            except Exception:
                result[feature] = np.nan

    if "company" in result.columns and "year" in result.columns:

        result = result.sort_values(
            ["company", "year"]
        ).reset_index(drop=True)

        for output_feature, base_feature in YOY_BASE_FEATURES.items():

            if base_feature in result.columns:

                result[output_feature] = (
                    result.groupby("company")[base_feature]
                    .pct_change()
                    * 100
                )

        if "revenue_per_employee" in result.columns:

            result["revenue_per_employee_growth"] = (
                result.groupby("company")["revenue_per_employee"]
                .pct_change()
                * 100
            )

        if "revenue_yoy" in result.columns and "net_income_yoy" in result.columns:

            result["revenue_profit_divergence"] = (
                result["revenue_yoy"]
                - result["net_income_yoy"]
            )

        if "debt_yoy" in result.columns and "revenue_yoy" in result.columns:

            result["debt_growth_vs_revenue_growth"] = (
                result["debt_yoy"]
                - result["revenue_yoy"]
            )

        if (
            "operating_cash_flow_yoy" in result.columns
            and "net_income_yoy" in result.columns
        ):

            result["cash_flow_profit_gap"] = (
                result["operating_cash_flow_yoy"]
                - result["net_income_yoy"]
            )

        if "net_profit_margin" in result.columns:

            result["margin_expansion"] = (
                result.groupby("company")["net_profit_margin"]
                .diff()
            )

            result["margin_compression"] = (
                result["margin_expansion"]
                .where(result["margin_expansion"] < 0, 0)
            )

        if "net_profit_margin" in result.columns:

            result["profitability_trend"] = (
                result.groupby("company")["net_profit_margin"]
                .pct_change()
                * 100
            )

    result = result.replace(
        [np.inf, -np.inf],
        np.nan
    )

    return result


def build_feature_analysis(df):

    enriched_df = calculate_feature_values(df)

    analysis_rows = []

    for feature_key, definition in FEATURE_CATALOG.items():

        if feature_key in enriched_df.columns:

            values = enriched_df[feature_key]

            valid_values = values.notna().sum()

            if valid_values > 0:

                status = (
                    "Available"
                    if feature_key in df.columns
                    else "Calculated"
                )

                latest_value = values.dropna().iloc[-1]

                analysis_rows.append({
                    "feature": feature_key,
                    "name": definition["name"],
                    "category": definition["category"],
                    "unit": definition["unit"],
                    "status": status,
                    "latest_value": latest_value,
                    "description": definition["description"]
                })

            else:

                analysis_rows.append({
                    "feature": feature_key,
                    "name": definition["name"],
                    "category": definition["category"],
                    "unit": definition["unit"],
                    "status": "Not provided",
                    "latest_value": None,
                    "description": definition["description"]
                })

        else:

            analysis_rows.append({
                "feature": feature_key,
                "name": definition["name"],
                "category": definition["category"],
                "unit": definition["unit"],
                "status": "Not provided",
                "latest_value": None,
                "description": definition["description"]
            })

    analysis_df = pd.DataFrame(analysis_rows)

    return {
        "data": enriched_df,
        "analysis": analysis_df,
        "total_features": len(FEATURE_CATALOG),
        "available_features": int(
            (analysis_df["status"] == "Available").sum()
        ),
        "calculated_features": int(
            (analysis_df["status"] == "Calculated").sum()
        ),
        "unavailable_features": int(
            (analysis_df["status"] == "Not provided").sum()
        )
    }


# FIN SIGHT PERMANENT DISCOVERY COMPATIBILITY PATCH
# ------------------------------------------------------------
# Keeps compatibility with the Streamlit UI while preserving
# the current Feature Intelligence result structure.
# ------------------------------------------------------------

_original_build_feature_analysis_compat = build_feature_analysis


def build_feature_analysis(df):

    result = _original_build_feature_analysis_compat(df)

    analysis_df = result.get("analysis")

    if analysis_df is None:
        return result

    mapped = {}
    available = []
    calculated = []
    unavailable = []

    for _, row in analysis_df.iterrows():

        feature = row["feature"]
        status = row["status"]

        if status == "Available":

            available.append(feature)

            mapped[feature] = {
                "source_column": feature,
                "group": row.get("category", "Other"),
                "type": "provided",
                "confidence": 1.0
            }

        elif status == "Calculated":

            calculated.append(feature)

            mapped[feature] = {
                "source_column": None,
                "group": row.get("category", "Derived Analysis"),
                "type": "calculated",
                "confidence": 1.0
            }

        else:

            unavailable.append(feature)

    catalog_features = set(FEATURE_CATALOG.keys())

    input_columns = set(
        str(column)
        for column in df.columns
    )

    unmapped = sorted(
        input_columns - catalog_features
    )

    discovery = {
        "mapped": mapped,
        "available": available,
        "calculated": calculated,
        "unavailable": unavailable,
        "unmapped": unmapped
    }

    result["discovery"] = discovery

    result["available_feature_count"] = len(available)

    result["extra_column_count"] = len(unmapped)

    result["derived_metric_count"] = len(calculated)

    return result

